### ISSUE TITLE
Alle wp-admin-resources som lastes inn bør bruke statisk path til ukm.no, ikke current blog

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMresources#3]
Bedre å cache 1 fil, heller enn 1 fil per blogg

**Comment by mariusmandal** [comment]
Spesielt når det er samme fil

**Comment by mariusmandal** [comment]
## Gjenskape problemet

- Logg inn i arrangørsystemet
- Velg en kommune
- Velg et arrangement
- Vis sidekilden

Her vil alle våre inkluderte resources ligge med path relativ til current blog, f.eks.:
```html
<link rel='stylesheet' id='UKMresources_wp-admin-css'  href='https://ukm.dev/2021-deatnu-tana-deatnu-tanalokalt/wp-content/plugins/UKMresources/css/UKMresources_wp-admin.css?ver=5.6.2' media='all' />
```

mens den egentlig burde vært
```html
<link rel='stylesheet' id='UKMresources_wp-admin-css'  href='https://ukm.dev/wp-content/plugins/UKMresources/css/UKMresources_wp-admin.css?ver=5.6.2' media='all' />
```

**Comment by mariusmandal** [comment]
## Løsningsforslag
**Tilnærming:** koding

Gå gjennom alle våre plugins (start med [UKMNorge/UKMresources](https://github.com/UKMNorge/UKMresources)) og oppdater URL til alle filer vi refererer gjennom:
- [ ] `wp_enqueue_style`
- [ ] `wp_enqueue_script`
- [ ] `wp_register_style`
- [ ] `wp_register_script`

**Comment by slogan-15** [comment]
Resources ser ut til å komme med riktig lenke. Denne lenken ble sjekket:

- view-source:https://ukm.dev/wp-admin/network/index.php?page=UKMnettverket_kommune&omrade=5441&type=kommune

Det finnes ikke resources som har relativ path fra view-source.

**Comment by mariusmandal** [comment]
Når du sjekker https://ukm.dev/wp-admin/network, så er du på hovedbloggen, som svarer til ukm.no/ og dermed vil alle lenkene være riktig @slogan-15 

Men, hvis du velger en kommune, og åpner en arrangementsside, så bruker den relative lenker :/
